# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: '3.6'

services:
  app:
    ports:
      - '8000:8000'
      - '8080:5000'
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    environment: &environment
      - STAGE=local
      - PYFACEBOOK_DEBUG=True
    volumes:
      - .:/usr/src
    env_file:
      - .env
