# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

services:
  app:
    image: pyfacebook-app-test
    environment: &environment
      - STAGE=test
      - PYFACEBOOK_DEBUG=True
    build:
      args:
        stage: test
    volumes:
      - .:/usr/src
